In [1]:
import numpy as np

In [2]:
#Creating an array
my_list=[1,2,3]
x=np.array(my_list)

In [3]:
type(x)

numpy.ndarray

In [4]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]


In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
#Linearly spaced 12 no. between 0 and 10 in this case
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [13]:
np.linspace(0,10,49)

array([ 0.        ,  0.20833333,  0.41666667,  0.625     ,  0.83333333,
        1.04166667,  1.25      ,  1.45833333,  1.66666667,  1.875     ,
        2.08333333,  2.29166667,  2.5       ,  2.70833333,  2.91666667,
        3.125     ,  3.33333333,  3.54166667,  3.75      ,  3.95833333,
        4.16666667,  4.375     ,  4.58333333,  4.79166667,  5.        ,
        5.20833333,  5.41666667,  5.625     ,  5.83333333,  6.04166667,
        6.25      ,  6.45833333,  6.66666667,  6.875     ,  7.08333333,
        7.29166667,  7.5       ,  7.70833333,  7.91666667,  8.125     ,
        8.33333333,  8.54166667,  8.75      ,  8.95833333,  9.16666667,
        9.375     ,  9.58333333,  9.79166667, 10.        ])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [16]:
#Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
#Random Numbers, rand give uniform distribution which means equal probability for all no. to be picked
np.random.rand(1) #Random number between 0 and 1, Uniform distribution

array([0.78918498])

In [20]:
np.random.rand(5,4) #Generate a 5 by 4 matrix of random no. between 0 and 1

array([[0.32650781, 0.10029723, 0.26759725, 0.10237725],
       [0.25577387, 0.00100109, 0.50237548, 0.57120464],
       [0.81229137, 0.80876115, 0.8720962 , 0.83160368],
       [0.85573939, 0.91785875, 0.49902564, 0.06123401],
       [0.2582063 , 0.05109192, 0.02518975, 0.94895569]])

In [22]:
#Normal Distibution random no. generation 
np.random.randn(5,4) #The closer to 0 the no. is the closer it is to the mean

array([[-0.65295489,  0.1431084 ,  1.76719559, -0.31493552],
       [ 0.2859213 , -1.41819723,  0.8192702 ,  1.79711951],
       [-0.0565525 , -0.30408468,  0.89977154,  0.64507199],
       [-0.47488558, -0.89845281, -0.48517475, -1.10142974],
       [ 1.36255673,  1.03492303,  1.19702429,  0.88964961]])

In [27]:
#Random Integer
np.random.randint(1,100)

47

In [26]:
np.random.randint(1,100,10)

array([ 9, 23, 89, 92, 10, 68, 66, 83, 47, 71])

In [29]:
arr=np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5) #Reshaped 1d array into 5 by 5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.reshape(5,5).shape  #Shape gives the dimension of matrix

(5, 5)

In [38]:
ranarr=np.random.randint(1,100,30)
ranarr

array([11, 70, 22, 72, 58, 66, 40, 73, 90, 64, 95, 76, 86, 88, 84, 40, 99,
       44, 18, 33, 96, 30, 39, 11, 18,  3, 20, 38, 37, 89])

In [39]:
ranarr.max() #Grab highest number

99

In [40]:
ranarr.argmax() #Grab the index of highest number

16

In [41]:
ranarr.argmin() #Grab the index of minimum number

25

In [43]:
ranarr+ranarr  #Index based summation, you can observe that the ranarr is doubled because it is added in itself

array([ 22, 140,  44, 144, 116, 132,  80, 146, 180, 128, 190, 152, 172,
       176, 168,  80, 198,  88,  36,  66, 192,  60,  78,  22,  36,   6,
        40,  76,  74, 178])

In [45]:
ranarr-ranarr #Index based substraction, self explanatory

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
arr**3 #Cube

array([    0,     1,     8,    27,    64,   125,   216,   343,   512,
         729,  1000,  1331,  1728,  2197,  2744,  3375,  4096,  4913,
        5832,  6859,  8000,  9261, 10648, 12167, 13824], dtype=int32)

In [49]:
arr+10 #adding 10 in each element

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [50]:
np.max(arr) #First way to get max value

24

In [52]:
arr.max() #Second way to get max value

24

In [55]:
np.sin(arr) #Taking sin of arr

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])

In [57]:
np.log(arr) #Taking log of arr, we get a warning because it doesn't make sense to take a log of 0 and it gets replaces by -inf

C:\Users\ZEESHAN\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [58]:
np.exp(arr)  #exponential of arr

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
arr[0:10]=100  #Broadcasting
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [69]:
sl_array=arr[0:10]   #Slicing the array
sl_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [70]:
sl_array[:]=99      #Assigning to each member of slice of array
sl_array

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [71]:
arr   #Notice that the original arr changed, slice was a pointer to the original array. Similar to pass by reference

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr_cp=arr.copy() #take a copy of array

In [73]:
arr_cp

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
arr_cp[:]=200

In [75]:
arr_cp   #The copy is changed

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [76]:
arr   #But the original is intact, it is similar to pass by copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [78]:
arr > 20  #Which elements are greater than 20 

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True])

In [79]:
arr[arr>20] #The actual values higher than 20

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 21, 22, 23, 24])